### ISSUE TITLE
exception after running script

### ISSUE THREAD

**Issue by bleugray** [btchmistry/REDbetter3#2]
I seem to be consistently receiving this error after the script completes.  

Traceback (most recent call last):
  File "/home/xxxxx/REDbetter3/redactedapi.py", line 494, in upload
    parsed = json.loads(r.content)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./redactedbetter.py", line 403, in <module>
    main()
  File "./redactedbetter.py", line 363, in main
    response = api.upload(torrent_group, api_torrent, new_torrent, format, description)
  File "/home/xxxxx/REDbetter3/redactedapi.py", line 505, in upload
    raise RequestException(e)
redactedapi.RequestException: Expecting value: line 1 column 1 (char 0)

**Comment by btchmistry** [comment]
can you provide the torrent ID this happens on + what command line arguments you provided?
